### ISSUE TITLE
How to build RTI connext DDS on aarch64 ?

### ISSUE THREAD

**Issue by Vermounthlly** [NXP/dds-tsn#1]
I have downloaded the installation package from RTI Free Trial:
`rti_connext_dds-6.1.1-lm-x64Linux4gcc7.3.0.run`
`rti_connext_dds-6.1.1-lm-target-armv8Linux4gcc7.3.0.rtipkg`

But I still don't understand how to build it .....
If anyone can help me????
Thank you !!!!!!!

target platform: raspberry-pi 4B
OS:Ubuntu20.04

**Comment by yuting-fu** [comment]
Hello @Vermounthlly, here's the official instruction from RTI for connext DDS 6.1.0: https://community.rti.com/static/documentation/connext-dds/6.1.0/doc/manuals/connext_dds_professional/getting_started_guide/index.html
For example, for cpp11 you can follow instructions in this document, Section 1.3: https://community.rti.com/static/documentation/connext-dds/6.1.0/doc/manuals/connext_dds_professional/getting_started_guide/cpp11/RTI_ConnextDDS_GettingStartedGuide_cpp11.pdf

**Comment by Vermounthlly** [comment]
Thank you for your reply!
But sorry ,I still have some questions.....
I've already installed the **_rti_connext_dds package_** and **_target-armv8Linux package_** on my PC(Ubuntu20.04) ,not on the raspberry-pi 4B(**it can't install them**).

I have the following 2 questions:
1. Could you be more specific about how to "build it on the arm64 target"? 
2. On the other hand, can I built it on the arch64 target using the same method?
![图片](https://user-images.githubusercontent.com/29684136/183363807-a2a1b89c-386c-49c1-b383-1d28490fb09b.png)

**Comment by yuting-fu** [comment]
Hi @Vermounthlly, we installed the armv8Linux package on a Linux host machine using the RTI Launcher as described in the [RTI document](https://community.rti.com/static/documentation/connext-dds/6.1.0/doc/manuals/connext_dds_professional/installation_guide/index.htm#installation_guide/Installing.htm%3FTocPath%3D_____3). Then we copied the whole installation to the target and built our ROS2-DDS-TSN application on the target against RTI DDS.

By the way, please make sure you have a 64Bit OS on your Raspberry Pi, such as [Ubuntu](https://ubuntu.com/download/raspberry-pi) or [Raspberry Pi OS 64-bit](https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit).

If you have more questions regarding RTI DDS, the best way is to contact [RTI support](https://www.rti.com/support) directly for up to date information.
