### ISSUE TITLE
Tool_traffic_analysis

### ISSUE THREAD

**Issue by djh12345678** [NXP/dds-tsn#2]
Hello, I'm using tool_ traffic_ When analyzing the message, I found that the tool seemed to count one packet less. I checked the code and found that the initial value was 0, and then parsed it to the desired Ethernet or rtps The data message is added to the original count by 1, but I don't know why the message counted several times is indeed one packet less, and I can't see what is wrong？

Using commands：sudo python3 traffic_analysis.py -p abc.pcapng -f rtps

Result:
 plugin         | name                                      | value
----------------+-------------------------------------------+-------------
 ethernet       | frame count                               | 432
                | VLAN frame count                          | 0
                | VLAN frame %                              | 0.0%
                | total frames size (bytes)                 | 68836
                | sniffing time (s)                         | 15.1
                | average frame size (bytes)                | 159.3
                | standard deviation of frame sizes (bytes) | 71.3
                | throughput (bytes/s)                      | 4553.7
 rtps.data      | data msg count                            | 202
                | data msg throughput (msgs/s)              | 20.2
                | data payload throughput (bytes/s)         | 1855.5
                | dropped packets                           | 0
                | dropped packets %                         | 0.00%
                | re-sent packets                           | 101
                | production interval: average time (s)     | 0.099163070
                | production interval: jitter (stdev) (s)   | 0.009965905
                | production interval: min time (s)         | 0.000000000
                | production interval: max time (s)         | 0.100329876
                | production interval: max-min diff (s)     | 0.100329876
                | packet transmission: average time (s)     | 0.000035737
                | packet transmission: jitter (stdev) (s)   | 0.000004788
                | packet transmission: min time (s)         | 0.000025988
                | packet transmission: max time (s)         | 0.000051975
                | packet transmission: max-min diff (s)     | 0.000025988
 rtps.frame     | frame count                               | 432
                | VLAN frame count                          | 0
                | VLAN frame %                              | 0.0%
                | total frames size (bytes)                 | 68836
                | average frame size (bytes)                | 159.3
                | standard deviation of frame sizes (bytes) | 71.3
                | sniffing time (s)                         | 15.1
                | throughput (bytes/s)                      | 4553.7
 rtps.intervals | average interval (s)                      | 0.035073014
                | jitter (stdev) of intervals (s)           | 0.131617846

But my pcapng has ethernet  433 packets and rtps.data 203 packets 

pacpng:
[abc.zip](https://github.com/NXP/dds-tsn/files/9502450/abc.zip)

**Comment by terechko** [comment]
Hi @djh12345678, thanks for submitting this issue! I can reproduce it on my machine. I'll check with developers about how to resolve it and get back to you.

**Comment by terechko** [comment]
Ah, I think I see the problem. Your packet count in the `pcapng` file indeed has 433 Ethernet packets, including 432 RTPS UDP packets and one more UDP packet. However, in the command line for `traffic_analysis.py` you specify the processing filter with `-f rtps` option. This option restricts _all_ the packets being processed from the input, leaving us with only 432 RTPS UDP Ethernet packets. If you remove the filter, you'll see all the packets from your file included in the statistics:
```
andrei@rp-thinkpad:~/src/dds-tsn$ python3 ./tools/traffic_analysis/traffic_analysis.py -p ~/tmp/abc.pcapng -f rtps
...
Statistics with a global pyshark filter: None
 plugin         | name                                      | value
----------------+-------------------------------------------+-------------
 ethernet       | frame count                               | 433
                | VLAN frame count                          | 0
                | VLAN frame %                              | 0.0%
                | total frames size (bytes)                 | 68879
                | sniffing time (s)                         | 15.1
                | average frame size (bytes)                | 159.1
                | standard deviation of frame sizes (bytes) | 71.4
                | throughput (bytes/s)                      | 4556.2
 rtps.data      | data msg count                            | 202
                | data msg throughput (msgs/s)              | 20.2
                | data payload throughput (bytes/s)         | 1855.5
                | dropped packets                           | 0
                | dropped packets %                         | 0.00%
                | re-sent packets                           | 101
                | production interval: average time (s)     | 0.099163060
                | production interval: jitter (stdev) (s)   | 0.009965900
                | production interval: min time (s)         | 0.000000000
                | production interval: max time (s)         | 0.100325823
                | production interval: max-min diff (s)     | 0.100325823
                | packet transmission: average time (s)     | 0.000031160
                | packet transmission: jitter (stdev) (s)   | 0.000004037
                | packet transmission: min time (s)         | 0.000024080
                | packet transmission: max time (s)         | 0.000044823
                | packet transmission: max-min diff (s)     | 0.000020742
 rtps.frame     | frame count                               | 432
                | VLAN frame count                          | 0
                | VLAN frame %                              | 0.0%
                | total frames size (bytes)                 | 68836
                | average frame size (bytes)                | 159.3
                | standard deviation of frame sizes (bytes) | 71.3
                | sniffing time (s)                         | 15.1
                | throughput (bytes/s)                      | 4553.7
 rtps.intervals | average interval (s)                      | 0.035073014
                | jitter (stdev) of intervals (s)           | 0.131617846

```
Before the statistics report you can also notice the string on console stating which global `pyshark` filter was used for the analysis, which in your case was:
```
Statistics with a global pyshark filter: rtps
```

I hope this resolves your problem. :blush:

**Comment by djh12345678** [comment]
Thank you very much!    i get,It is work!
